# Site settings
title: Hilojack Blog
email: a132811@gmail.com
description: 'Coder'
baseurl: ""
url: "http://hilojack.com"
username: hilojack

# Build settings
markdown: kramdown
paginate: 5 
paginate_path: "/p:num"
permalink: /p/:title
